# Generated by Django 5.2.17 on 2026-09-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentprofile_grade_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="interests",
            field=models.ManyToManyField(blank=True, to="accounts.interest"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="skills",
            field=models.ManyToManyField(blank=True, to="accounts.skill"),
        ),
    ]
